# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.cpg
canonical: http://hl7.org/fhir/uv/cpg
name: CPG
title: Clinical Practice Guidelines
description: Implementation guidance for creating Clinical Practice Guidelines with formal artifacts to facilitate sharing and implementation of the guideline
status: active # draft | active | retired | unknown
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg  #<<< must include a http://hl7.org/fhir/StructureDefinition/structuredefinition-wg extension that identifies the workgroup responsible for the IG. This is the authoritative element.
    valueCode: cds  # <<< The value must be the code for the workgroup
version: 2.0.0-ballot
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ballot # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World"
publisher:
  name: HL7 International / Clinical Decision Support
  url:  http://www.hl7.org/Special/committees/dss
  # email: test@example.org

# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
#
# dependencies:
#   hl7.fhir.us.core: 3.1.0
#   hl7.fhir.us.mcode:
#     id: mcode
#     uri: http://hl7.org/fhir/us/mcode/ImplementationGuide/hl7.fhir.us.mcode
#     version: 1.0.0
#

dependencies:
  hl7.terminology: 5.5.0
  hl7.fhir.uv.extensions: 5.1.0

#
# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
#
pages:
  index.md:
    title: CPG Home
  approach.md:
    documentation-approach-12-conceptual-knowledge-architecture.md:
      title: CPG Knowledge Architecture-Conceptual Perspective
      documentation-approach-12-01-separations-of-concerns-in-the-cpg.md:
        title: Separations of Concerns
      documentation-approach-12-02-separating-and-defining-case-plan-and-workflow.md:
        title: Separating and Defining Case, Plan, and Workflow
      documentation-approach-12-03-cpg-plan.md:
        title: CPGPlan
      documentation-approach-12-04-cpg-case.md:
        title: CPGCase
      documentation-approach-12-05-cpg-careplan.md:
        title: CPGCarePlan
      documentation-approach-12-06-cpg-common-pathway.md:
        title: Workflow and Common Pathway
      documentation-approach-12-07-cpg-derivative-and-related-assets.md:
        title: CPGGuideline and Derivative & Related Assets
    documentation-approach-04-guideline-development.md:
      title: Guideline Development
      documentation-approach-04-01-guideline-development-group.md:
        title: Guideline Development Group
      documentation-approach-04-02-guideline-development-frameworks.md:
        title: Guideline Development Frameworks
      documentation-approach-04-03-6S-evidence-pyramid-and-learning-health-systems.md:
        title: 6S Evidence Pyramid and Learning Health Systems
      documentation-approach-04-04-analysis-of-evidence-recommendations-reporting.md:
        title: Analysis of Evidence, Recommendations, and Reporting
      documentation-approach-04-05-computable-guideline-artifacts.md:
        title: Development of Computable Clinical Guideline Artifacts
    documentation-approach-05-knowledge-engineering-overview.md:
      title: Knowledge Engineering Overview
      documentation-approach-05-01-knowledge-acquisition.md:
        title: Knowledge Acquisition
      documentation-approach-05-02-knowledge-translation.md:
        title: Knowledge Translation
      documentation-approach-05-03-knowledge-representation.md:
        title: Knowledge Representation/Expression
      documentation-approach-05-04-knowledge-execution-and-validation.md:
        title: Knowledge Execution and Validation
      documentation-approach-05-05-knowledge-implementation.md:
        title: Knowledge Implementation
      documentation-approach-05-06-agile-cpg-development-approach.md:
        title: Agile CPG Development Approach
    documentation-approach-02-04-knowledge-representation.md:
      title: Knowledge Representation Overview
      documentation-approach-06-knowledge-representation.md:
        title: Knowledge Representation
      documentation-approach-06-01-levels-of-knowledge-representation.md:
        title: “Levels” of Knowledge Representation Framing
      documentation-approach-07-tiers-of-functionality.md:
        title: Tiers of Functionality
      documentation-approach-08-levels-of-representation-by-tiers-of-functionality.md:
        title: Levels of Representation by Tiers of Functionality
      documentation-approach-06-02-knowledge-assets.md:
        title: Knowledge Assets
      documentation-approach-06-03-knowledge-architecture.md:
        title: Knowledge Architecture
    documentation-approach-02-05-knowledge-implementation.md:
      title: Implementation Computable Knowledge
      documentation-approach-09-methods-of-implementation.md:
        title: Methods of Implementation
        activityflow.md:
          title: Activity Flow
        documentation-careplanning.md:
          title: Evidence-Based Care Planning
      documentation-approach-10-mechanisms-of-integration.md:
        title: Mechanisms of Integration
      documentation-approach-03-conformance-levels.md:
        title: Levels of Enablement
      documentation-conformance.md:
        title: Conformance
  methodology.md:
  profiles.md:
    title: Profile Definitions and Documentation
  terminology.md:
  libraries.md:
  artifacts.md:
  examples.md:
    examples-activities.md:
      title: Activity Examples
    examples-chf.md:
      title: Congestive Heart Failure Example
    examples-hiv-guideline.md:
      title: HIV Screening Guideline Recommendations
    methodology-case-study.md:
      title: Methodology Example - COVID-19 Severity Classification
  downloads.md:
  glossary.md:
  checklists.md:
    clinical-guidelines-development-L1-checklist.md:
      title: L1 Checklist
    clinical-guidelines-development-L2-checklist.md:
      title: L2 Checklist
    clinical-guidelines-development-L3-checklist.md:
      title: L3 Checklist
    clinical-guidelines-development-L4-checklist.md:
      title: L4 Checklist
  packaging.md:
    title:  Artifact Packaging
  documentation-methodology.md:
    title: Mapping and Other Formalisms
  common-care-pathway.md:
    title: Common Care Pathway
  changes.md:
    title: Version History

#
# The parameters property represents IG.definition.parameter. Rather
# than a list of code/value pairs (as in the ImplementationGuide
# resource), the code is the YAML key. If a parameter allows repeating
# values, the value in the YAML should be a sequence/array.
# For parameters defined by core FHIR see:
# http://build.fhir.org/codesystem-guide-parameter-code.html
# For parameters defined by the FHIR Tools IG see:
# http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
#
parameters:
  apply-contact: true
  apply-publisher: true
  apply-version: true
  apply-jurisdiction: true
  apply-license: true
  apply-copyright: true
  apply-wg: true
  path-history: http://hl7.org/fhir/uv/cpg/history.html
  path-binary: ./input/cql
  path-resource: 
    - ./input/vocabulary/codesystem
    - ./input/vocabulary/valueset
  special-url-base: http://hl7.org/fhir

#
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │ The menu property will be used to generate the input/menu.xml file. The menu is represented    │
# │ as a simple structure where the YAML key is the menu item name and the value is the URL.       │
# │ The IG publisher currently only supports one level deep on sub-menus. To provide a             │
# │ custom menu.xml file, do not include this property and include a `menu.xml` file in            │
# │ input/includes. To use a provided input/includes/menu.xml file, delete the "menu"              │
# │ property below.                                                                                │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Approach: approach.html
  Methodology: methodology.html
  Profiles: profiles.html
  Terminology: terminology.html
  Libraries: libraries.html
  Artifacts: artifacts.html
  Examples: examples.html
  Downloads: downloads.html
  Glossary: glossary.html
  Version History: changes.html

# ╭───────────────────────────Less Common Implementation Guide Properties──────────────────────────╮
# │  Uncomment the properties below to configure additional properties on the ImplementationGuide  │
# │  resource. These properties are less commonly needed than those above.                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#
# Those who need more control or want to add additional details to the contact values can use
# contact directly and follow the format outlined in the ImplementationGuide resource and
# ContactDetail.
#
# contact:
#   - name: Bob Smith
#     telecom:
#       - system: email # phone | fax | email | pager | url | sms | other
#         value: bobsmith@example.org
#         use: work
#
#
# The global property corresponds to the IG.global property, but it
# uses the type as the YAML key and the profile as its value. Since
# FHIR does not explicitly disallow more than one profile per type,
# neither do we; the value can be a single profile URL or an array
# of profile URLs. If a value is an id or name, SUSHI will replace
# it with the correct canonical when generating the IG JSON.
#
# global:
#   Patient: http://example.org/fhir/StructureDefinition/my-patient-profile
#   Encounter: http://example.org/fhir/StructureDefinition/my-encounter-profile
#
#
# The resources property corresponds to IG.definition.resource.
# SUSHI can auto-generate all of the resource entries based on
# the FSH definitions and/or information in any user-provided
# JSON or XML resource files. If the generated entries are not
# sufficient or complete, however, the author can add entries
# here. If the reference matches a generated entry, it will
# replace the generated entry. If it doesn't match any generated
# entries, it will be added to the generated entries. The format
# follows IG.definition.resource with the following differences:
#   * use IG.definition.resource.reference.reference as the YAML key.
#   * if the key is an id or name, SUSHI will replace it with the
#     correct URL when generating the IG JSON.
#   * specify "omit" to omit a FSH-generated resource from the
#     resource list.
#   * if the exampleCanonical is an id or name, SUSHI will replace
#     it with the correct canonical when generating the IG JSON.
#   * groupingId can be used, but top-level groups syntax may be a
#     better option (see below).
# The following are simple examples to demonstrate what this might
# look like:
#
# resources:
  # ImplementationGuide/hl7.fhir.uv.cpg.chf: omit #omit this because this template does not generate HTML for IG, so the link from TOC fails
#   Patient/my-example-patient:
#     name: My Example Patient
#     description: An example Patient
#     exampleBoolean: true
#   Patient/bad-example: omit
#
#
# Groups can control certain aspects of the IG generation.  The IG
# documentation recommends that authors use the apply groups that
# are provided by the templating framework, but if authors want to
# use their own instead, they can use the mechanism below.  This will
# create IG.definition.grouping entries and associate the individual
# resource entries with the corresponding groupIds. If a resource
# is specified by id or name, SUSHI will replace it with the correct
# URL when generating the IG JSON.
#
# groups:
#   GroupA:
#     name: Group A
#     description: The Alpha Group
#     resources:
#     - StructureDefinition/animal-patient
#     - StructureDefinition/arm-procedure
#   GroupB:
#     name: Group B
#     description: The Beta Group
#     resources:
#     - StructureDefinition/bark-control
#     - StructureDefinition/bee-sting
#
#
# The ImplementationGuide resource defines several other properties
# not represented above. These properties can be used as-is and
# should follow the format defined in ImplementationGuide:
# * date
# * meta
# * implicitRules
# * language
# * text
# * contained
# * extension
# * modifierExtension
# * experimental
# * useContext
# * copyright
# * packageId
#
#
# ╭──────────────────────────────────────────SUSHI flags───────────────────────────────────────────╮
# │  The flags below configure aspects of how SUSHI processes FSH.                                 │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# The FSHOnly flag indicates if only FSH resources should be exported.
# If set to true, no IG related content will be generated.
# The apply value for this property is false.
#
# FSHOnly: false
#
#
# When set to true, the "short" and "definition" field on the root element of an Extension will
# be set to the "Title" and "Description" of that Extension. apply is true.
#
# applyExtensionMetadataToRoot: true
#
#
# The instanceOptions property is used to configure certain aspects of how SUSHI processes instances.
# See the individual option definitions below for more detail.
#
instanceOptions:
  # When set to true, slices must be referred to by name and not only by a numeric index in order to be used
  # in an Instance's assignment rule. All slices appear in the order in which they are specified in FSH rules.
  # While SUSHI applys to false for legacy reasons, manualSliceOrding is recommended for new projects.
  manualSliceOrdering: true # true | false
  # Determines for which types of Instances SUSHI will automatically set meta.profile
  # if InstanceOf references a profile:
  #
  # setMetaProfile: always # always | never | inline-only | standalone-only
  #
  #
  # Determines for which types of Instances SUSHI will automatically set id
  # if InstanceOf references a profile:
  #
  # setId: always # always | standalone-only
